config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  get 'what_we_do', to: 'pages#what_we_do'
  get 'our_case_studies', to: 'pages#our_case_studies'
  get 'management_team', to: 'pages#management_team'
  get 'press_media', to: 'pages#press_media'
  get 'contact_us', to: 'pages#contact_us'
  get 'downloadbrochure', to: 'application#download_brochure'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'downloadvcard/:name', to: 'pages#vcard', as: 'downloadvcard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/case_study.rb
class CaseStudy < ApplicationRecord
  belongs_to :category
  mount_uploader :photo, PhotoUploader
  validates_presence_of :title, :summary, :description
  validates :priority, inclusion: { in: [nil, 1, 2, 3, 4, 5, 6], message: "must be a number between 1 and 6" }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :case_studies
end

app/models/press_release.rb
class PressRelease < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  validates_presence_of :date
  validates_presence_of :title
  validates_presence_of :body
  validates_presence_of :first_paragraph

  def formatted_date
    self.date ? self.date.strftime('%d %b, %Y') : ""
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:download_brochure]

  def download_brochure
    send_file "#{Rails.root}/app/assets/Addington_Capital_Brochure.pdf", type: "application/pdf", x_sendfile: true
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @latest_press_releases = PressRelease.order(date: :desc).first(5)
  end

  def what_we_do
  end

  def our_case_studies
    @retail_case_studies = CaseStudy.where(category_id: 1).order(:priority)
    @residential_case_studies = CaseStudy.where(category_id: 2).order(:priority)
    @offices_case_studies = CaseStudy.where(category_id: 3).order(:priority)
  end

  def management_team
  end

  def press_media
    @press_releases = PressRelease.order(date: :desc)
  end

  def contact_us
  end

  def vcard
    case params[:name]
      when 'roberts'
        send_file "#{Rails.root}/app/assets/vcards/Martin Roberts.vcf", x_sendfile: true
      when 'allen'
        send_file "#{Rails.root}/app/assets/vcards/Matthew Allen.vcf", x_sendfile: true
      when 'ramlugun'
        send_file "#{Rails.root}/app/assets/vcards/Roshan Ramlugun.vcf", x_sendfile: true
      when 'shellabear'
        send_file "#{Rails.root}/app/assets/vcards/Helen Shellabear.vcf", x_sendfile: true
      when 'symonds'
        send_file "#{Rails.root}/app/assets/vcards/Philip Symonds.vcf", x_sendfile: true
      when 'cornford'
        send_file "#{Rails.root}/app/assets/vcards/Tim Cornford.vcf", x_sendfile: true
      when 'mcgovern'
        send_file "#{Rails.root}/app/assets/vcards/Mike McGovern.vcf", x_sendfile: true
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'addington_capital_favicon.ico' %>
    <title>Addington Capital</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/_archive_press_cuttings.html.erb
<hr>
<div class="archive-news-post">
	<div class="news-date">
		<p>Posted in News on <%= press_release.formatted_date if press_release %></p>
	</div>
	<div class="news-snippet">
		<div class="news-title">
			<p><span><%= press_release.title if press_release %></span></p>
			<div class="news-brief" id="archive-brief-<%= press_release.id %>">
				<p><%= press_release.first_paragraph if press_release %></p>
				<h6><%= link_to "[ READ MORE... ]", "#", class: 'archive-read-more','data-target' => "#archive-#{press_release.id}" %></h6>
			</div>
			<div class="full-news hidden slideDown" id="archive-<%= press_release.id %>">
      <%= cl_image_tag(press_release.photo, width: 400, height: 200, crop: :fill) if press_release.photo? %>
				<p><%= simple_format press_release.body.html_safe if press_release %></p>
				<br>
        <p>Posted in News on <%= press_release.formatted_date if press_release %></p>
				<h6><%= link_to "[ CLOSE ]", "#", class: "archive-close", 'data-target' => "#archive-brief-#{press_release.id}" %></h6>
			</div>
		</div>
	</div>
</div>

app/views/pages/_contact_details.html.erb
<div class="contact-text text-center">
	<p class="contact-address">41-42 Eastcastle Street, London, W1W 8DU</p>
	<p><span>T: </span>+44 (0)20 7042 9250</p>
	<p><span>E: </span><%= link_to "info@addingtoncapital.com", "mailto:info@addingtoncapital.com" %></p>
  <br>
  <!-- <div class="registered-office">
    <p>Registered Office<br>
      Company No. 0897648<br>
      Vat No. 7456390287<br>
      Registered In England & Wales</p>
  </div> -->
  <div class="contacts">
      <div class="main-contact">
        <h6>PRINCIPAL</h6>
        <p>Martin Roberts</p>
        <p><span>E: </span><%= link_to "martin@addingtoncapital.com", "mailto:martin@addingtoncapital.com" %></p>
      </div>
      <div class="main-contact">
        <h6>PRINCIPAL</h6>
        <p>Matthew Allen</p>
        <p><span>E: </span><%= link_to "matthew@addingtoncapital.com", "mailto:matthew@addingtoncapital.com" %></p>
      </div>
      <div class="main-contact">
        <h6>PRESS AND MEDIA</h6>
        <p>Karen Roberts</p>
        <p><span>E: </span><%= link_to "karen@addingtoncapital.com", "mailto:karen@addingtoncapital.com" %></p>
      </div>
  </div>
</div>
<div class="contact-img">
  <%= image_tag "6818-Addliving-Map.jpg" %>
</div>


<!-- <script>
  function initMap() {
    var addCap = {lat: 51.5166, lng: -0.1396};
    var map = new google.maps.Map(document.getElementById('map'), {
      center: addCap,
      zoom: 17,
      styles: [
      {
          "featureType": "water",
          "elementType": "geometry",
          "stylers": [
              {
                  "color": "#e9e9e9"
              },
              {
                  "lightness": 17
              }
          ]
      },
      {
          "featureType": "landscape",
          "elementType": "geometry",
          "stylers": [
              {
                  "color": "#f5f5f5"
              },
              {
                  "lightness": 20
              }
          ]
      },
      {
          "featureType": "road.highway",
          "elementType": "geometry.fill",
          "stylers": [
              {
                  "color": "#ffffff"
              },
              {
                  "lightness": 17
              }
          ]
      },
      {
          "featureType": "road.highway",
          "elementType": "geometry.stroke",
          "stylers": [
              {
                  "color": "#ffffff"
              },
              {
                  "lightness": 29
              },
              {
                  "weight": 0.2
              }
          ]
      },
      {
          "featureType": "road.arterial",
          "elementType": "geometry",
          "stylers": [
              {
                  "color": "#ffffff"
              },
              {
                  "lightness": 18
              }
          ]
      },
      {
          "featureType": "road.local",
          "elementType": "geometry",
          "stylers": [
              {
                  "color": "#ffffff"
              },
              {
                  "lightness": 16
              }
          ]
      },
      {
          "featureType": "poi",
          "elementType": "geometry",
          "stylers": [
              {
                  "color": "#f5f5f5"
              },
              {
                  "lightness": 21
              }
          ]
      },
      {
          "featureType": "poi.park",
          "elementType": "geometry",
          "stylers": [
              {
                  "color": "#dedede"
              },
              {
                  "lightness": 21
              }
          ]
      },
      {
          "elementType": "labels.text.stroke",
          "stylers": [
              {
                  "visibility": "on"
              },
              {
                  "color": "#ffffff"
              },
              {
                  "lightness": 16
              }
          ]
      },
      {
          "elementType": "labels.text.fill",
          "stylers": [
              {
                  "saturation": 36
              },
              {
                  "color": "#333333"
              },
              {
                  "lightness": 40
              }
          ]
      },
      {
          "elementType": "labels.icon",
          "stylers": [
              {
                  "visibility": "off"
              }
          ]
      },
      {
          "featureType": "transit",
          "elementType": "geometry",
          "stylers": [
              {
                  "color": "#f2f2f2"
              },
              {
                  "lightness": 6
              }
          ]
      },
      {
        "featureType": "administrative",
        "elementType": "geometry.fill",
        "stylers": [
          {
              "color": "#fefefe"
          },
          {
              "lightness": 20
          }
        ]
      },
      {
        "featureType": "administrative",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#fefefe"
            },
            {
                "lightness": 17
            },
            {
                "weight": 1.2
            }
          ]
        }
      ],
      maxZoom: 17,
      minZoom: 10,
      zoomControl: false,
      streetViewControl: false,
      gestureHandling: 'none'
    });
    var marker = new google.maps.Marker({
      position: addCap,
      map: map,
      icon: { url: "assets/AddingtonCapitalMapLogo.png" }
    });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);
  }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD4BcjJFqqwD2SQsmnJLh0egu_B8pu5Yqc&callback=initMap">
</script> -->

app/views/pages/home.html.erb
<%= render 'shared/navbar_landing' %>
<div class="banner-landing" id="home-main">
	<div class="banner-content" id="Wrapper">
		<h1>Addington Capital:</h1>
		<h3>Mission Statement </h3>
		<h4>"To be the operating partner of choice for value investors active in the UK real estate markets."</h4>
	    <!-- <h5>23rd Jan 2017</h5>
	    <h6><%= link_to "[ READ MORE ]...", press_media_path %></h6> -->
		<%= link_to "https://twitter.com/AddingtonCap", target: "_blank" do %>
			<%= image_tag "Addington_Capital_Twitter_logo.png", class: "social-media-icon" %>
		<% end %>
		<%= link_to "https://www.linkedin.com/company/addington-capital-llp/", target: "_blank" do %>
			<%= image_tag "Addington_Capital_LinkedIn_logo.png", class: "social-media-icon" %>
		<% end %>
	</div>
	<div class="more-press-landing text-center">
		<h6>[ MORE PRESS ]</h6>
		<%= link_to "" do %>
			<%= image_tag "Addington_Capital_down.png" "#press", class: "hand-icon-landing", id: "header-page-down" %>
		<% end %>
	</div>
</div>
<div class="press-wrapper" id="press">
	<div class="pressmedia">
		<p class="press-title">PRESS & MEDIA</p>
		<div class="home-press-tabs">
			<h5><%= link_to "LATEST NEWS", "" %></h5>
			<h5><%= link_to "NEWS ARCHIVE", press_media_path(:anchor => 'news-archive') %></h5>
		</div>
		<div class="latest-news">
			<div class="dotted-line"></div>
	    <% @latest_press_releases.each do |press_release| %>
			  <%= render 'pages/press_cuttings', press_release: press_release %>
	    <% end %>
		</div>
    <div id="whatwedo"></div>
		<div class="hand-icon-press text-center">
			<%= link_to "" do %>
				<%= image_tag "Addington_Capital_down_black.png", class: "hand-icn-press", id: "press-page-down" %>
			<% end %>
		</div>
	</div>
</div>
<div class="what-we-do-margin hidden"></div>
<div class="what-we-do-wrapper" id="what-we-do">
	<%= link_to "", class: "about-arrow-left" do %>
		<%= image_tag "Addington_Capital_arrow_left.png", class: "arrow" %>
	<% end %>
	<div class="what-we-do text-center">
		<h1>WHAT WE DO</h1>
		<h4>Addington is an active investor and manager of assets in the office, retail and residential markets in the UK. We understand property and have a strong track record of unlocking and creating value. We bring creative thinking and an experienced management team to maximise investment returns through asset and development management.
		</h4>
    <span>
  		<div class="what-we-do-links">
          <h5 class="active" data-target=".about-retail">RETAIL</h5>
          <h5 data-target=".about-residential">RESIDENTIAL</h5>
          <h5 data-target=".about-offices">OFFICES</h5>
  		</div>
    </span>
    <div class="what-we-do-content">
  		<div class="about about-retail active">
  			<h3>RETAIL</h3>
  			<h5>We have national retail experience ranging from small shops to town centre dominant shopping centres, with expertise in the restaurant and leisure sector</h5>
        <%= link_to our_case_studies_path do %>
      		<h6>[ VIEW ALL CASE STUDIES... ]</h6>
      	<% end %>
  		</div>

  		<div class="about about-residential">
  			<h3>RESIDENTIAL</h3>
  			<h5>Addington has acquired residential portfolios and individual blocks of apartments across the UK. We develop, refurbish, manage and let or sell.</h5>
        <%= link_to our_case_studies_path(anchor: 'home-residential') do %>
          <h6>[ VIEW ALL CASE STUDIES... ]</h6>
        <% end %>
  		</div>

      <div class="about about-offices">
        <h3>OFFICES</h3>
        <h5>We actively manage, refurbish and redevelop offices in central London, the south east and in office markets throughout the UK.</h5>
        <%= link_to our_case_studies_path(anchor: 'home-offices') do %>
          <h6>[ VIEW ALL CASE STUDIES... ]</h6>
        <% end %>
      </div>

    </div>
	</div>
	<%= link_to "", class: "about-arrow-right" do %>
		<%= image_tag "Addington_Capital_arrow_right.png", class: "arrow" %>
	<% end %>
</div>
<div class="spacer">
	<div class="text-center">
		<%= link_to "" do %>
			<%= image_tag "Addington_Capital_down_white.png", class: "hand-icn-about", id: "what-we-do-page-down"%>
		<% end %>
	</div>
</div>
<div class="blue-contact-wrapper">
	<div class="contact-text text-center">
  <h2 style="padding: 20px 0px 10px 0px;">CONTACT US</h2>
  <p class="contact-address">41-42 Eastcastle Street, London, W1W 8DU</p>
  <p><span>T: </span>+44 (0)20 7042 9250</p>
  <p><span>E: </span><%= link_to "info@addingtoncapital.com", "mailto:info@addingtoncapital.com" %></p>
  <div class="contact-img">
    <%= image_tag "6818-Addliving-Map.jpg" %>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="spacer">
	<div class="hand-icon-contact text-center">
		<%= link_to "" do %>
			<%= image_tag "Addington_Capital_up_white.png", class: "hand-icn-contact", id:"back-to-top" %>
		<% end %>
	</div>
</div>
<div class="footer">
	<div class="vertical-line">
		<div class="footer-page-links footer-child">
			<p><%= link_to "Home", root_path %><br>
			<%= link_to "What We Do", what_we_do_path %><br>
			<%= link_to "Our Case Studies", our_case_studies_path %><br>
			<%= link_to "Management Team", management_team_path %><br>
			<%= link_to "Press & Media", press_media_path %><br>
			<%= link_to "Contact Us", contact_us_path %></p>
		</div>
	</div>
	<div class="vertical-line">
		<div class="footer-address footer-child">
			<p>41-42 Eastcastle Street<br>
			London<br>
			W1W 8DU<br>
			<br>
			+44 (0)20 7042 9250<br>
			<%= link_to "info@addingtoncapital.com", "mailto:info@addingtoncapital.com" %> </p>
		</div>
	</div>
	<div class="vertical-line">
		<!-- <div class="footer-official footer-child">
			<p>Registered Office<br>
			Company No. 0897648<br>
			Vat No. 7456390287<br>
			Registered In England & Wales</p>
		</div> -->
		<div class="sm-icons-footer">
			<%= link_to "https://twitter.com/AddingtonCap", target: "_blank" do %>
				<%= image_tag "Addington_Capital_Twitter_logo.png", class: "social-media-icon" %>
			<% end %>
			<%= link_to "https://www.linkedin.com/company/addington-capital-llp/", target: "_blank" do %>
				<%= image_tag "Addington_Capital_LinkedIn_logo.png", class: "social-media-icon" %>
			<% end %>
		</div>
	</div>
	<div class="vertical-line vertical-line-hidden-mob">
		<div class="footer-brochure-img footer-child">
			<%= image_tag "http://res.cloudinary.com/dqxvcdy6w/image/upload/v1497288388/Screen_Shot_2017-06-12_at_18.25.56_xjesi1.png" %>
		</div>
	</div>
	<div class="vertical-line-last">
		<div class="footer-brochure">
			<%= link_to "Download Brochure", downloadbrochure_path %>
		</div>
	</div>


<!-- mobile -->
<div class="mobile">
	<div class="sm-icons-footer-mob">
		<%= link_to "https://www.twitter.com", target: "_blank" do %>
			<%= image_tag "Addington_Capital_Twitter_logo.png", class: "social-media-icon" %>
		<% end %>
		<%= link_to "https://www.linkedin.com", target: "_blank" do %>
			<%= image_tag "Addington_Capital_LinkedIn_logo.png", class: "social-media-icon" %>
		<% end %>
		<%= link_to "https://www.facebook.com", target: "_blank" do %>
			<%= image_tag "Addington_Capital_Facebook_logo.png", class: "social-media-icon" %>
		<% end %>
	</div>
	<div class="footer-brochure-mob">
		<%= link_to "Download Brochure", downloadbrochure_path %>
	</div>
	<div class="footer-brochure-img-mob footer-child">
		<%= image_tag "http://res.cloudinary.com/dqxvcdy6w/image/upload/v1497288388/Screen_Shot_2017-06-12_at_18.25.56_xjesi1.png" %>
	</div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-addcap navbar-addcap-fixed hidden-xs hidden-sm">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-addcap-brand" do %>
    <%= image_tag "Addington_Capital_logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-addcap-right">

<!-- Navbar menu -->
    <!-- Home link -->
    <div class="outline">
      <%= link_to "HOME", root_path, class: "navbar-addcap-link" %>
    </div>
    <!-- What we do link -->
    <div class="link-outline">
      <%= link_to "WHAT WE DO", root_path(:anchor => "what-we-do-jump"), class: "navbar-addcap-link" %>
    </div>
      <!-- Properties  link -->
    <div class="link-outline">
      <%= link_to "OUR PROPERTIES", our_properties_path, class: "navbar-addcap-link" %>
    </div>
      <!-- Team link -->
    <div class="link-outline">
      <%= link_to "MANAGEMENT TEAM", management_team_path, class: "navbar-addcap-link" %>
    </div>
      <!-- Press link -->
    <div class="link-outline">
      <%= link_to "PRESS & MEDIA", press_media_path, class: "navbar-addcap-link" %>
    </div>
      <!-- Contact link -->
    <div class="link-outline">
      <%= link_to "CONTACT US", contact_us_path, class: "navbar-addcap-link" %>
    </div>
  </div>
</div>



<!-- Dropdown list appearing on mobile only -->
<div class="navbar-addcap navbar-addcap-fixed hidden-md hidden-lg">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-addcap-brand" do %>
    <%= image_tag "" %>
  <% end %>
  <div class="navbar-addcap-item hidden-md hidden-lg">
    <div class="dropdown toggle-white">
      <a class="fa fa-bars dropdown-toggle" data-toggle="dropdown" href="#"></a>
      <ul class="dropdown-menu dropdown-menu-right navbar-addcap-dropdown-menu">
        <li><%= link_to "HOME", root_path %></li>
        <li><%= link_to "WHAT WE DO", what_we_do_path %></li>
        <li><%= link_to "OUR PROPERTIES", our_properties_path %></li>
        <li><%= link_to "MANAGEMENT TEAM", management_team_path %></li>
        <li><%= link_to "PRESS & MEDIA", press_media_path %></li>
        <li><%= link_to "CONTACT US", contact_us_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_landing.html.erb
<div class="navbar-addcap-landing navbar-addcap-fixed hidden-xs hidden-sm">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-addcap-brand" do %>
    <%= image_tag "Addington_Capital_logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-addcap-right">

<!-- Navbar menu -->
    <!-- Home link -->
    <div class="outline">
      <%= link_to "HOME", root_path, class: "navbar-addcap-link" %>
    </div>
    <!-- What we do link -->
    <div class="link-outline">
      <%= link_to "WHAT WE DO", "", class: "navbar-addcap-link", id: 'what-we-do-link' %>
    </div>
      <!-- Properties  link -->
    <div class="link-outline">
      <%= link_to "OUR CASE STUDIES", our_case_studies_path, class: "navbar-addcap-link" %>
    </div>
      <!-- Team link -->
    <div class="link-outline">
      <%= link_to "MANAGEMENT TEAM", management_team_path, class: "navbar-addcap-link" %>
    </div>
      <!-- Press link -->
    <div class="link-outline">
      <%= link_to "PRESS & MEDIA", press_media_path, class: "navbar-addcap-link" %>
    </div>
      <!-- Contact link -->
    <div class="link-outline">
      <%= link_to "CONTACT US", contact_us_path, class: "navbar-addcap-link" %>
    </div>
  </div>
</div>



<!-- Dropdown list appearing on mobile only -->
<div class="navbar-addcap-landing navbar-addcap-fixed hidden-md hidden-lg">
  <div class="navbar-addcap-item hidden-md hidden-lg">
    <div class="dropdown toggle-white">
      <a class="fa fa-bars dropdown-toggle" data-toggle="dropdown" href="#"></a>
      <ul class="dropdown-menu dropdown-menu-right navbar-addcap-dropdown-menu">
        <li><%= link_to "HOME", root_path %></li>
        <li><%= link_to "WHAT WE DO", "", id: 'what-we-do-mobile-link' %></li>
        <li><%= link_to "OUR CASE STUDIES", our_case_studies_path %></li>
        <li><%= link_to "MANAGEMENT TEAM", management_team_path %></li>
        <li><%= link_to "PRESS & MEDIA", press_media_path %></li>
        <li><%= link_to "CONTACT US", contact_us_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_main.html.erb
<div class="navbar-addcap navbar-addcap-fixed hidden-xs hidden-sm">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-addcap-brand" do %>
    <%= image_tag "Addington_Capital_logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-addcap-right">

<!-- Navbar menu -->
    <!-- Home link -->
    <div class="outline">
      <%= link_to "HOME", root_path, class: "navbar-addcap-link" %>
    </div>

  <!-- specific to navbar main -->
    <!-- What we do link -->
    <div class="link-outline">
      <%= link_to "WHAT WE DO", root_path(:anchor => "whatwedo"), class: "navbar-addcap-link", id: "whatwedolink" %>
    </div>
  <!-- specific to navbar main -->

      <!-- Case Studies  link -->
    <div class="link-outline">
      <%= link_to "OUR CASE STUDIES", our_case_studies_path, class: "navbar-addcap-link" %>
    </div>
      <!-- Team link -->
    <div class="link-outline">
      <%= link_to "MANAGEMENT TEAM", management_team_path, class: "navbar-addcap-link" %>
    </div>
      <!-- Press link -->
    <div class="link-outline">
      <%= link_to "PRESS & MEDIA", press_media_path, class: "navbar-addcap-link" %>
    </div>
      <!-- Contact link -->
    <div class="link-outline">
      <%= link_to "CONTACT US", contact_us_path, class: "navbar-addcap-link" %>
    </div>
  </div>
</div>



<!-- Dropdown list appearing on mobile only -->
<div class="navbar-addcap navbar-addcap-fixed hidden-md hidden-lg">
  <!-- Logo -->
  <%= link_to root_path, class: "mobile-logo" do %>
    <%= image_tag "Addington_Capital_logo.png" %>
  <% end %>
  <div class="navbar-addcap-item hidden-md hidden-lg">
    <div class="dropdown toggle-white">
      <a class="fa fa-bars dropdown-toggle" data-toggle="dropdown" href="#"></a>
      <ul class="dropdown-menu dropdown-menu-right navbar-addcap-dropdown-menu">
        <li><%= link_to "HOME", root_path %></li>
        <li><%= link_to "WHAT WE DO", root_path(anchor: 'whatwedo') %></li>
        <li><%= link_to "OUR CASE STUDIES", our_case_studies_path %></li>
        <li><%= link_to "MANAGEMENT TEAM", management_team_path %></li>
        <li><%= link_to "PRESS & MEDIA", press_media_path %></li>
        <li><%= link_to "CONTACT US", contact_us_path %></li>
      </ul>
    </div>
  </div>
</div>